### ISSUE TITLE
Raspberry Zero and img image

### ISSUE THREAD

**Issue by kajaba** [AdrianHome/AdrianSmartAssistant#7]
Is it possible to write a quick list of required packages/modules for raspberry? I cant use the image on your site (too big for my sdcard). But I clone this git but there seems to be some problem with node. But it seems some packages need to be installed (like mpg123). It would be great if you provide some list. 
Thank you for doing great job :)
Is it possible to run Adrian on raspi zero?

**Comment by bbbenji** [comment]
Giving people the requirements and steps to manually install Adrian on a distro would be great. Also less work for devs, no need to create new images all the time. Though this project seems to have died down which is a shame because it's a great idea and had a great start. Hope it picks back up.

**Comment by jamiedeakin** [comment]
Hey guys, apologies for the lack of feedback recently on the project. We've had a lot going on so finding time to dedicate to this has been difficult. As you mentioned we made some really good progress with this to begin with so we're hoping to pick back up now.

I have just merged an update that includes a package.json file for easier install of the required node modules. if you clone the latest master of the project, create the constants.js as described in the README then run 'npm install' in the root directory it should get you up and running on a pi.

If you have any issue just let me know.

**Comment by kajaba** [comment]
Well npm install gives me lots of errors:

npm install
npm WARN package.json setenv@1.0.3 No repository field.
npm WARN engine grpc@1.2.0: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@4.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine joi@9.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine items@2.1.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine topo@2.0.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine isemail@2.2.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})

> sleep@5.1.0 install /home/pi/AdrianSmartAssistant/node_modules/sleep
> node-gyp rebuild

make: Entering directory '/home/pi/AdrianSmartAssistant/node_modules/sleep/build'
  CXX(target) Release/obj.target/node_sleep/sleep.o
In file included from ../sleep.cc:2:0:
../node_modules/nan/nan.h:324:47: error: 'REPLACE_INVALID_UTF8' is not a member of 'v8::String'
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
node_sleep.target.mk:82: recipe for target 'Release/obj.target/node_sleep/sleep.o' failed
make: *** [Release/obj.target/node_sleep/sleep.o] Error 1
make: Leaving directory '/home/pi/AdrianSmartAssistant/node_modules/sleep/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.4.34+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/AdrianSmartAssistant/node_modules/sleep
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! sleep@5.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@5.1.0 install script.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.34+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/AdrianSmartAssistant
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
-
> node-expat@2.3.15 install /home/pi/AdrianSmartAssistant/node_modules/xml2json/node_modules/node-expat
> node-gyp rebuild

make: Entering directory '/home/pi/AdrianSmartAssistant/node_modules/xml2json/node_modules/node-expat/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
../deps/libexpat/lib/xmlparse.c: In function 'gather_time_entropy':
../deps/libexpat/lib/xmlparse.c:709:7: warning: variable 'gettimeofday_res' set but not used [-Wunused-but-set-variable]
   int gettimeofday_res;
       ^
^C

**Comment by bbbenji** [comment]
Can confirm similar errors when running `npm install` on latest Raspbian. This might be a Debian problem.

**Comment by jamiedeakin** [comment]
Hey guys, I solved this issue by updating the node version. The version that installs as standard on the latest release of raspbian is pretty old. There's some good instructions here:

http://thisdavej.com/upgrading-to-more-recent-versions-of-node-js-on-the-raspberry-pi/
